### ISSUE TITLE
Conversion to A-Frame possible?

### ISSUE THREAD

**Issue by NAHIDMA** [yomotsu/meshwalk#22]
Hi  @yomotsu. Is there any major rework needed to work this code in a-frame?  I tried to make it work with a-frame with a sphere and a plane, but the sphere keeps falling down

**Comment by yomotsu** [comment]
Sorry, I'm not familiar with a-frame🥲

**Comment by NAHIDMA** [comment]
Thank you for the quick reply. It's ok. A-frame is basically a framework in html that helps to create various meshes in in Three.js using html like tags called <a-entity>
